include: package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_collection_literal: ignore
    sort_pub_dependencies: ignore

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    public_member_api_docs: false
    avoid_catching_errors: false
    no_default_cases: false
    avoid_positional_boolean_parameters: false
    unawaited_futures: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    avoid_redundant_argument_values: false
    unnecessary_lambdas: false
    no_runtimeType_toString: false
    avoid_dynamic_calls: false
    parameter_assignments: false
    use_setters_to_change_properties: false
    flutter_style_todos: false
    prefer_asserts_with_message: false
    omit_local_variable_types: false
    one_member_abstracts: false
    comment_references: false
    avoid_print: true